### PR TITLE
Fix type safety warnings in server and client

### LINKED ISSUE #16: Warnings about type safety need to be addressed
In both client and server, when using JSONSimple, there are warnings:

> Type safety: The method put(Object, Object) belongs to the raw type HashMap. References to generic type HashMap<K,V> should be parameterized

Code should have no warnings, no errors. Considering this a bug.

### PR DESCRIPTION
**Pull request by Ohiekkar**
Instead of applying the fix in three different methods of the client I abstracted the functionality of creating the JSON string for the request to a helper method similarly to how the response is created on the server.

This will also make #7 easier as now there's only one place in the client where the change has to be done.

Fixes #16

### CODE REVIEW

File: JEasyCryptoClient/src/CryptoClient.java [hunk 1]
```diff
@@ -5,6 +5,9 @@
 import java.net.InetAddress;
 import java.net.SocketException;
 import java.net.UnknownHostException;
+import java.util.HashMap;
+import java.util.Map;
```
Comment (mbuet2ner) [inline JEasyCryptoClient/src/CryptoClient.java]: Do we really need `Map` at this point, or can we just go with `HashMap` alone?

File: JEasyCryptoClient/src/CryptoClient.java [hunk 2]
```diff
@@ -137,39 +140,38 @@ private String enterText(String prompt, boolean required) {
...
-		request.put("method", method);
-		request.put("data", text);
-		String data = request.toJSONString();
+		String data = createRequest("decrypt", method, text);
 		DatagramPacket packet = new DatagramPacket(data.getBytes(), data.length(), serverAddr, serverPort);
 		socket.send(packet);
 	}
+
+	private String createRequest(String operation, String method, String text) {
+		Map<String, Object> requestMap = new HashMap<>();
```
Comment (mbuet2ner) [inline JEasyCryptoClient/src/CryptoClient.java]: I think it would be better to use an `HashMap` object directly instead of `Map`. I think we can be more specific at this point,

File: JEasyCryptoServer/src/CryptoServer.java [hunk 3]
```diff
@@ -3,6 +3,8 @@
 import java.net.DatagramSocket;
 import java.net.InetAddress;
 import java.net.SocketException;
+import java.util.HashMap;
+import java.util.Map;
```
Comment (mbuet2ner) [inline JEasyCryptoServer/src/CryptoServer.java]: Same applies here

File: JEasyCryptoServer/src/CryptoServer.java [hunk 4]
```diff
@@ -101,11 +103,14 @@ public void run() {
 	} // end run()
 	
 	private String createResponse(String op, long id, EasyCryptoAPI.Result result) {
-		JSONObject toSend = new JSONObject();
-		toSend.put("id", id);
-		toSend.put("operation", op+"-response");
-		toSend.put("result", result.resultCode().ordinal());
-		toSend.put("data", result.result());
-		return toSend.toJSONString();
+		Map<String, Object> responseMap = new HashMap<>();
```
Comment (mbuet2ner) [inline JEasyCryptoServer/src/CryptoServer.java]: Same applies here

**Comment by Ohiekkar** [comment]
Updated PR to use HashMap only.
